// svelte_template/src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Moon, Sun } from 'lucide-svelte'
  import { theme } from '$lib/stores/theme'

  /**
   * ThemeToggle - Button to toggle between light and dark themes
   *
   * Displays a sun icon in dark mode and moon icon in light mode.
   */
</script>

<button
  on:click={() => theme.toggleTheme()}
  class="p-2 rounded-lg bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors duration-200"
  aria-label="Toggle theme"
  title={`Switch to ${$theme === 'light' ? 'dark' : 'light'} mode`}
>
  {#if $theme === 'light'}
    <Moon class="w-5 h-5 text-gray-700" />
  {:else}
    <Sun class="w-5 h-5 text-yellow-400" />
  {/if}
</button>

// react_template/src/components/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react'
import { useTheme } from '@/contexts/ThemeContext'

/**
 * ThemeToggle - Button to toggle between light and dark themes
 *
 * Displays a sun icon in dark mode and moon icon in light mode.
 */
export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme()

  return (
    <button
      onClick={toggleTheme}
      className="p-2 rounded-lg bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors duration-200"
      aria-label="Toggle theme"
      title={`Switch to ${theme === 'light' ? 'dark' : 'light'} mode`}
    >
      {theme === 'light' ? (
        <Moon className="w-5 h-5 text-gray-700" />
      ) : (
        <Sun className="w-5 h-5 text-yellow-400" />
      )}
    </button>
  )
}
